version: '3.9'
services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'