spring:
  application:
    name: course-catalog-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_create: true
        hbm2ddl:
          auto: create-drop # this recreates the db, not recommended for production
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true
#  h2:
#    console:
#      enabled: true


message: Hello from default profile

#---
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#message: Hello from prod profile